name: CI

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      # 通知更新
      - name: Run a one-line script
        run: curl https://dev.biji.io/actions?sign=${{ secrets.SIGN }}&url=https://github.com/Tokinx/Wing/archive/${{ github.ref }}.zip
        
